### ISSUE TITLE
バトルスコアページのNext Over Damageの値がおかしい

### ISSUE THREAD

**Issue by code0001aaa** [ProjectPrimera/ongeki-score#100]
### 現象
バトルスコアページのNext Over Damageの値がおかしい

### 発生日時
常に発生する

### ユーザーID
654

### 再現方法
https://ongeki-score.net/user/654/battle にアクセスしたときのNext Over Damageの値がおかしい

### OSバージョン
Windows 10

### ブラウザ
Google Chrome バージョン:76.0.3809.100

### その他
画像のNextの部分です
![kancolle_20190819-050423365](https://user-images.githubusercontent.com/54248547/63229754-d4797000-c23e-11e9-8d4e-e3420414fee6.jpg)

**Comment by Slime-hatena** [comment]
@code0001aaa ご報告ありがとうございます。 初めて見ましたなんだこれ・・・
小数点3桁あるので切り下げ処理も上手く行ってないですね・・・
原因分かり次第修正します。

**Comment by code0001aaa** [comment]
https://github.com/Slime-hatena/ProjectPrimera/blob/2c807a5d1c3e6fa737fff1f22d623f2547dd696a/OngekiScoreLog/app/ScoreData.php#L74
この部分、正しくは

```php
$this->value[$key]->over_damage_high_score_next = floor((100.0 - fmod($this->value[$key]->over_damage_high_score, 100.0)) * pow(10, 2)) / pow(10, 2);
```

ではないでしょうか？

**Comment by Slime-hatena** [comment]
@code0001aaa 大変遅くなり申し訳ございません。こちら修正を行いました。次回リリースで修正されます。誠にありがとうございます。
